export const MailUnreadContainer = 'cf'
export const MailUnreadH5 = 'mb0 pa3 blue'
export const MailUnreadContainerMessages = 'ph1'
export const MailUnreadUl = 'list ph4-l pa0 cf'

export const MailUnreadMessageLi = 'fl w-48-l bg-white mb1 pa3 ba b--moon-gray br2 cf mb2-l'
export const MailUnreadButton = 'br2 ph3 pv2 mt3 bg-blue white ba b--blue ws-normal pointer tl pointer'
export const MailUnreadContainerSubject = 'mb4 pb4 bb b--moon-gray cf'
export const MailUnreadSubject = 'b tl'
export const MailUnreadFrom = 'tl'
export const MailUnreadDate = 'tl'
export const MailUnreadDelete = 'blue pointer tl'
export const MailUnreadContainerBody = 'cb pb4 bb b--moon-gray tl'
export const MailUnreadContainerBtn = 'tc'
