export const MailReadContainer = 'cf'
export const MailReadH5 = 'mb0 pa3 pt0 blue'
export const MailReadContainerMessages = 'ph1'
export const MailReadUl = 'list ph4-l pa0 cf'

export const MailReadMessageLi = 'bg-white mb1 mb4-l pv3 ph3 ba b--moon-gray br2 cf'
export const MailReadButton = 'br2 ph3 pv2 mt3 mt0-l bg-orange white ba b--orange ws-normal pointer'
export const MailReadContainerMessage = 'relative-l fr-l w-90-l ph3-l pt0-l'
export const MailReadSubject = 'b tl'
export const MailReadFrom = 'tl'
export const MailReadContainerDate = 'absolute-l top-0-l right-0-l tl tr-l'
export const MailReadDate = 'moon-gray'
export const MailReadDelete = 'blue pointer'
export const MailReadContainerBody = 'mt3 tl'
export const MailReadContainerBtn = 'pt1-l'
